#!/bin/ash

# System Shutdown Script
#

. /etc/rc.d/init.d/functions

echo
echo "System is going down for reboot or halt now." >> /dev/ttyprintk
echo


echo "Starting stop scripts." >> /dev/ttyprintk

for i in /etc/rc.d/stop/*
do
	if [ -x $i ]; then
		$i stop
	fi
done

if [ -x /sbin/hwclock ] && [ -e /dev/rtc0 ]; then
	echo -n "Syncing system clock to hardware clock: " >> /dev/ttyprintk
	hwclock --systohc --utc
	check_status
fi

if [ -x /sbin/swapoff ] && [ -s /etc/fstab ]; then
	echo -n "Disabling swap space: " >> /dev/ttyprintk
	swapoff -a
	check_status
fi

echo -n "Syncing all filesystems: " >> /dev/ttyprintk
sync
check_status

echo -n "Unmounting all filesystems: " >> /dev/ttyprintk
umount -a -r

